export const FETCH_BARCODE = 'FETCH_BARCODE';
export const SET_LOGIN = 'SET_LOGIN';
export const SET_LOGOUT = 'SET_LOGOUT';
export const ADD_TICKET = 'ADD_TICKET';
export const GET_TICKET = 'GET_TICKET';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const REMOVE_FLASH_MESSAGE = 'REMOVE_FLASH_MESSAGE';